language: node_js
node_js: 8
cache:
  directories:
  - node_modules
script:
- npm run build
- npm test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: yFfpJWvcEzSFiApFEyzt/YfOv9VKBOHZQG5WY3w58i+e/prLcYC6+c8deIda2cIwRJjdgb3dTDYfiCpAeLsc3JuAiGiYbLxAgZNSnFgV58FeKTqoglzYWVoNon7OwQfstNfLkSnMj936PykOWtFnzkmXwucbW0h/LJ8pStS+d6sFyNqHcJHIysTZJRGBFPzOG6g1WVGLdr/XGZOZB96dOrVHB1tOHNB5GKs6XgFnHPnWbSCXUZa6Owon5TQ6+eEAg3FLS5l+2zdVDN6g+9GdYVEtrKQNfb8rjwcncV2qM/EawXdPa8f16UbFLOpbLwJXpL6ugcfqQ8Lz1My9b7+LwBY1MgeeodBoSXAyxXCH8vi3LhAhI8ut7lR+gHhCmLP9HyfoNme918zy39tiQJ2Pl2FdeSyS8jXzeQvSLKYweFU8SoCPPmqUngKPje1ZgJQk9OOke3aK08W6jA+tpndoEZ026l6U0yRKbBQozvsAmAW5DJwlxc4YB12JVlB+gtkWqgaKm7m/P0iorhNgWhNXBvmGgBtpmm6pYzPA7UrWVgEheO09IyUGXmK/lQsnUIc4FMl3LoHqlWwq90QoWOMV2tPjvVcgZr4FRjUTi+Ej+9HqflKij/+PY1ldNBFer1dKf4h/QPiLhfD2gos4u7gMRoqn8GqXznIlIMaLdF4a4V8=
  keep_history: true
  on:
    branch: gh-pages
  
