language: node_js
node_js: 8
cache:
  directories:
  - node_modules
script:
- npm run build
- npm test
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token:
    secure: g0sAL7v1J4jlNXN3++H8iI4lKRxHbDGLv9Ek3YyciOA0SDa/JrogtDCcGPGFeOYSiUscUSv39QqzbpVT9Jzv6b28HvYHq+lJkWl9by1GFB7BjR3tGxYKPQHfHxr7yWSSST3lJNT7nKIQPAWLjcu2cfMl4T8QF4nkILyRvr44+ejVw7wdaYK7wwN9XrPE/wuM5l5hwdQj0GoqoL8Ulm2+WVuV80oo0MnPDaXaOvbJpjlIdqKYQrum87oCpWUHXbUme1TVia8cOC5z4lykV0bZiA/nWniUUe3a4APVeGVZmBp6gIiRE3XeufoOYjs8dxq/U7E5r/mZe3UFrEI/yYo1We09DFcml3r35H3TGMokjMZtQVWJO49yo9XOTYfrksU1vlUo5xqy/DzvT2PRLgDSswu9okcKCj/Jl7P11jxztBHCKseVW3aVUqDl+7hFHU/Xgf9kNrYbbUckl1X+9JFc1S+wL2X3xogFVSu1Qjc8Kbx5ha7jkF6Hw49SzcxZfYAukNr/p8vymPSSptBtlQKhX4zlF8XDjIAp2PdHDLv/WXRWJ4mOA/PCV4jGE4V2OARrAkwMxbFbcvcvVwFkIb1t7vndY5r+MpJjk7oHhoEXS7HtQPRGRi94CmeWDOgq0QYfyuUArIhJnc/iqA5A2R8HYZu/dKIIsL81Oa1RFgGI2pM=
  on:
    branch: master
